# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
target 'mycard' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for mycard
  pod 'RealmSwift'
  pod 'TextFieldEffects'
  pod 'JSSAlertView'
  pod 'SVProgressHUD'
  pod 'DZNEmptyDataSet'
  pod 'IQKeyboardManagerSwift'
  pod 'Parse'
  pod 'iCarousel'
  pod 'SwiftValidator'
  pod 'ParseUI'  
end
